routes/admin.php
<?php

// Route::get('/home', function () {
//     $users[] = Auth::user();
//     $users[] = Auth::guard()->user();
//     $users[] = Auth::guard('admin')->user();

//     //dd($users);

//     return view('admin.home');
// })->name('home');


Route::group(['middleware' => ['admin']], function() {

	Route::namespace('backend')->group(function () {

        Route::get('/home', function () {
            $users[] = Auth::user();
            $users[] = Auth::guard()->user();
            $users[] = Auth::guard('admin')->user();

            //dd($users);

            return view('admin.home');
        })->name('home');
		// Route::get('home', 'HomeController@index')->name('home');

        Route::get('applications-datatable','ApplicationController@Datatable')->name('applications.datatable');
	    Route::resource('applications', 'ApplicationController');
		
    });

});

routes/web.php
<?php

// use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('application');
    // return redirect('/home');
});

// Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['namespace'=>'App\Http\Controllers'], function () {
	Route::resource('applications', 'ApplicationController');
});
Route::group(['prefix' => 'admin', 'namespace'=>'App\Http\Controllers\backend\AdminAuth'], function () {
  Route::get('/login', 'LoginController@showLoginForm')->name('admin.login');
  Route::post('/login', 'LoginController@login');
  Route::post('/logout', 'LoginController@logout')->name('admin.logout');
  Route::get('/logout', 'LoginController@logout')->name('admin.logout');

  // Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
  // Route::post('/register', 'AdminAuth\RegisterController@register');

  // Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
  // Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
  // Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
  // Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

app/Models/Application.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'email', 'address', 'gender', 'ssc_university', 'ssc_year', 'ssc_percentage', 'hsc_university', 'hsc_year', 'hsc_percentage', 'graduation_university', 'graduation_year', 'graduation_percentage', 'master_degree_university', 'master_degree_year', 'master_degree_percentage', 'lang1', 'lang1_read', 'lang1_write', 'lang1_speak', 'lang2', 'lang2_read', 'lang2_write', 'lang2_speak', 'lang3', 'lang3_read', 'lang3_write', 'lang3_speak', 'tech_lang1', 'tech_lang1_type', 'tech_lang2', 'tech_lang2_type', 'tech_lang3', 'tech_lang3_type', 'tech_lang4', 'tech_lang4_type', 'preferred_location', 'expected_ctc', 'current_ctc', 'notice_period'
    ];

    public function work_experiences() {
        return $this->hasMany('App\Models\WorkExperience');
    }
}

app/Http/Controllers/ApplicationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Application;
use App\Models\WorkExperience;

use Redirect;

class ApplicationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('application');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|string|unique:applications',    		
            'address' => 'required',
            'gender' => 'required',
            'ssc_university' => 'required',
            'ssc_year' => 'required',
            'ssc_percentage' => 'required',
            'hsc_university' => 'required',
            'hsc_year' => 'required',
            'hsc_percentage' => 'required',
            'graduation_university' => 'required',
            'graduation_year' => 'required',
            'graduation_percentage' => 'required',
            'master_degree_university' => 'required',
            'master_degree_year' => 'required',
            'master_degree_percentage' => 'required',
            'preferred_location' => 'required',
            'expected_ctc' => 'required',
            'current_ctc' => 'required',
            'notice_period' => 'required',
        ]);

        $input = $request->except(['_token']);        
        $application = Application::Create($input);

        $company_name_array = $request->company_name;
        $designation_array = $request->designation;
        $from_date_array = $request->from_date;
        $to_date_array = $request->to_date;

        if(!empty($company_name_array)){
            foreach ($company_name_array as $key => $price) {
                //collect all inserted record IDs
                $single_array = ['application_id' => $application->id, 'company_name' => $company_name_array[$key], 'designation' => $designation_array[$key], 'from_date' => $from_date_array[$key], 'to_date' => $to_date_array[$key]]; 
                WorkExperience::Create($single_array);
            }
        }

        return Redirect::route('applications.index')->with('success', 'Application create successfully.');
        // dd($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/backend/ApplicationController.php
<?php

namespace App\Http\Controllers\backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\Application;
use App\Models\WorkExperience;

use DataTables;
use Response;
use Mail;
use Excel;
use Redirect;
use Image;
use File;
use Storage;

use App\Traits\Authorizable;

class ApplicationController extends Controller
{

    use Authorizable;
    
    public function __construct() {
        $this->middleware('auth:admin');
        //$this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.application.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $application = Application::find($id);
        if(empty($application)){
            return Redirect::route('admin.applications.index')->with('error','Application not found.');
        }
        return view('admin.application.edit',compact('application'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Application $application)
    {
        // $this->validate($request, [
        //     'name' => 'required|unique:blog_categories,name,'.$blog_category->id,            
        // ]);

        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|string|unique:applications,email,'.$application->id,    		
            'address' => 'required',
            'gender' => 'required',
            'ssc_university' => 'required',
            'ssc_year' => 'required',
            'ssc_percentage' => 'required',
            'hsc_university' => 'required',
            'hsc_year' => 'required',
            'hsc_percentage' => 'required',
            'graduation_university' => 'required',
            'graduation_year' => 'required',
            'graduation_percentage' => 'required',
            'master_degree_university' => 'required',
            'master_degree_year' => 'required',
            'master_degree_percentage' => 'required',
            'preferred_location' => 'required',
            'expected_ctc' => 'required',
            'current_ctc' => 'required',
            'notice_period' => 'required',
        ]);

        $input = $request->except(['_token','_method']);
        $input['lang1'] = (isset($request->lang1)) ? $request->lang1 : '';
        $input['lang1_read'] = (isset($request->lang1_read)) ? $request->lang1_read : '';
        $input['lang1_write'] = (isset($request->lang1_write)) ? $request->lang1_write : '';
        $input['lang1_speak'] = (isset($request->lang1_speak)) ? $request->lang1_speak : '';
        $input['lang2'] = (isset($request->lang2)) ? $request->lang2 : '';
        $input['lang2_read'] = (isset($request->lang2_read)) ? $request->lang2_read : '';
        $input['lang2_write'] = (isset($request->lang2_write)) ? $request->lang2_write : '';
        $input['lang2_speak'] = (isset($request->lang2_speak)) ? $request->lang2_speak : '';
        $input['lang3'] = (isset($request->lang3)) ? $request->lang3 : '';
        $input['lang3_read'] = (isset($request->lang3_read)) ? $request->lang3_read : '';
        $input['lang3_write'] = (isset($request->lang3_write)) ? $request->lang3_write : '';
        $input['lang3_speak'] = (isset($request->lang3_speak)) ? $request->lang3_speak : '';

        $input['tech_lang1'] = (isset($request->tech_lang1)) ? $request->tech_lang1 : '';
        $input['tech_lang1_type'] = (isset($request->tech_lang1_type)) ? $request->tech_lang1_type : '';
        $input['tech_lang2'] = (isset($request->tech_lang2)) ? $request->tech_lang2 : '';
        $input['tech_lang2_type'] = (isset($request->tech_lang2_type)) ? $request->tech_lang2_type : '';
        $input['tech_lang3'] = (isset($request->tech_lang3)) ? $request->tech_lang3 : '';
        $input['tech_lang3_type'] = (isset($request->tech_lang3_type)) ? $request->tech_lang3_type : '';
        $input['tech_lang4'] = (isset($request->tech_lang4)) ? $request->tech_lang4 : '';
        $input['tech_lang4_type'] = (isset($request->tech_lang4_type)) ? $request->tech_lang4_type : '';

        $application->update($input);

        $company_name_array = $request->company_name;
        $designation_array = $request->designation;
        $from_date_array = $request->from_date;
        $to_date_array = $request->to_date;

        WorkExperience::where('application_id', '=', $application->id)->delete();
        if(!empty($company_name_array)){
            foreach ($company_name_array as $key => $price) {
                //collect all inserted record IDs
                $single_array = ['application_id' => $application->id, 'company_name' => $company_name_array[$key], 'designation' => $designation_array[$key], 'from_date' => $from_date_array[$key], 'to_date' => $to_date_array[$key]]; 
                WorkExperience::Create($single_array);
            }
        }

        return Redirect::route('admin.applications.index')->with('success','Application update successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

        $Application = Application::find($id);
        if(!empty($Application)){
            $Application->delete();
        }
        
        if ($request->ajax()) {
            return response()->json(['status' => 'success', 'msg' => "Application deleted successfully."]);
        }
        return Redirect::route('admin.applications.index')->with('success','Application deleted successfully.');
    }

    public function Datatable(Request $request) {
        $raw = Application::query();
        $datatable = app('datatables')->of($raw)

        ->editColumn('created_at', function ($raw) {
            if($raw->created_at == ''){
                return '-';
            }else{
                return date('Y-m-d H:i:s A', strtotime($raw->created_at));
            }
        })

        ->addColumn('action', function ($raw) {
            $html = '';
            if(auth()->user()->can('edit_applications')){
                $html .= '<a href="'.route("admin.applications.edit", $raw->id).'" class="label theme-bg2 text-white f-12">Edit</a>  ';
            }
            if(auth()->user()->can('delete_applications')){
                $html .= '<a class="label theme-bg text-white f-12 delete-application-btn" href="javascript:void(0)" data-url="'. route("admin.applications.destroy", $raw->id) .'">Delete</a>';
            }
            return $html;
        });
        
        return $datatable->make(true);

    }

}

resources/views/admin/application/index.blade.php
@extends('admin.layout.app')

@section('content')
<!-- [ Main Content ] start -->
<section class="pcoded-main-container">
    <div class="pcoded-wrapper">
        <div class="pcoded-content">
            <div class="pcoded-inner-content">
                <!-- [ breadcrumb ] start -->
                <div class="page-header">
                    <div class="page-block">
                        <div class="row align-items-center">
                            <div class="col-md-12">
                                <div class="page-header-title">
                                    <h5 class="m-b-10">Application</h5>
                                </div>
                                <ul class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="{{ route('admin.home') }}"><i class="feather icon-home"></i></a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0)">Applications</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- [ breadcrumb ] end -->
                <div class="main-body">
                    <div class="page-wrapper">
                        <!-- [ Main Content ] start -->
                        <div class="row">

                            <!-- [ Hover-table ] start -->
                            <div class="col-xl-12">

                                @include('admin.layout.session')

                                <div class="card">
                                    <div class="card-header">
                                        <h5>Admins</h5>

                                        <div class="d-inline-block dropdown float-right">
                                            @can('add_applications')
                                                <a href="{{ route('admin.applications.create') }}" class="btn btn-glow-primary btn-primary btn-sm"><i class="feather icon-plus-circle"></i>Add New User</a>
                                            @endcan
                                            
                                        </div>
                                    </div>
                                    <div class="card-block table-border-style">
                                        <div class="table-responsive Recent-Users">
                                            <table class="table table-hover application_datatable">
                                                <thead>
                                                    <tr>
                                                        <th>Name</th>
                                                        <th>Email</th>
                                                        <th>Address</th>
                                                        @if(auth()->user()->can('edit_applications') || auth()->user()->can('delete_applications'))
                                                          <th>Action</th>
                                                        @endif
                                                    </tr>
                                                </thead>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- [ Hover-table ] end -->

                            
                        </div>
                        <!-- [ Main Content ] end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- [ Main Content ] end -->
@endsection

@push('js')
<script type="text/javascript">
$(function(){
        $('.applications').addClass('active');

    var oTable = $('.application_datatable').DataTable({
        processing: false,
        serverSide: true,
        ajax:'{!! route('admin.applications.datatable') !!}',
        columns: [
            {data: 'name', name: 'name', sortable: true, orderable: true, searchable: true},
            {data: 'email', name: 'email', sortable: true, orderable: true, searchable: true},
            {data: 'address', name: 'address', sortable: true, orderable: true, searchable: true},
            @if(auth()->user()->can('edit_applications') || auth()->user()->can('delete_applications'))
            {data: 'action', sortable: false,searchable: false},
            @endif
        ],

        @if(!auth()->user()->can('edit_applications') && !auth()->user()->can('delete_applications'))
            order: [[1, 'desc']],
        @elseif(auth()->user()->can('edit_applications') && auth()->user()->can('delete_applications'))
            order: [[2, 'desc']],
        @elseif(auth()->user()->can('edit_applications'))
            order: [[1, 'desc']],
        @elseif(auth()->user()->can('delete_applications'))
            order: [[2, 'desc']],
        @endif
        "pagingType": "full_numbers",
        "language": {
            // "emptyTable": "No fees",
            "search": '<span>Filter:</span> _INPUT_',
            "lengthMenu": '<span>Show:</span> _MENU_',
            "searchPlaceholder": "Search..."
            // "paginate": { 'first': 'First', 'last': 'Last', 'next': '&rarr;', 'previous': '&larr;' }
        },
        autoWidth: false,
        'fnDrawCallback': function( oSettings ) {
        }
    });


});
</script>
@endpush